model: YoutubeDNN
learning_rate: 1.0e-3
weight_decay: 0
dropout_p: 0.2
batch_size: 3000
embedding_dim: 16
user_hidden_units: [16, 16, 16]
loss: mse 
epochs: 10
save_checkpoint_periods: 1
optimizer: adam